### ISSUE TITLE
Collision for CBOR tag 560

### ISSUE THREAD

**Issue by setrofim** [ietf-rats-wg/draft-ietf-rats-corim#132]
CBOR tag `#6.560` is used for both `tagged-cert-path-thumbprint-type` and `tagged-bytes` types (See: https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#name-raw-values-types and https://ietf-rats-wg.github.io/draft-ietf-rats-corim/draft-ietf-rats-corim.html#name-crypto-keys).

**Comment by nedmsmith** [comment]
There are earmarks for specific CBOR tags for xcorim (525-527) and concise-evidence (570-571). Should these be included in the table? Should the repo maintain a local registry?

**Comment by nedmsmith** [comment]
fixed by PR #133
