### ISSUE TITLE
Verifier behavior for matching RVs to ACS containing Evidence Claims

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#143]
PR #107 lines 1458-1466, describe RV matching of Evidence in ACS, but instead focuses on matching Endorsements / Endorsed Value Claims. It is unclear if matching Endorsements is applied before/after RV matching. I believe EV matching happens after RV matching.

It would help if terminology was more pedantic in terms of identifying the type of claim contained in the ACS. I.e., "If any Reference Value Claim in a group does not match an Evidence Claim in the ACS then ..."

**Comment by andrew-draper** [comment]
The text commented on by this issue has been changes as part of PR #193.

Is it OK to close this issue?

**Comment by nedmsmith** [comment]
> Is it OK to close this issue?

OK by me.
