### ISSUE TITLE
PR 107 Confusing text

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats-wg/draft-ietf-rats-corim#144]
in Pull Request:
https://github.com/ietf-rats-wg/draft-ietf-rats-corim/pull/107

The following text is ambigous

A Reference Value consists of an `environment-map` plus a `measurement-map`. In the
`reference-values-triple-record` these are packaged together. In other triples multiple
Reference Values are represented more compactly by letting one `environment-map`
apply to multiple `measurement-map`s.

Need to re-write the same.

**Comment by thomas-fossati** [comment]
Can the issue description point out the exact ambiguity we want to address?  I guess in a couple of weeks all the cached context which now looks evident will be lost and we'll be left wondering what we meant and what needs doing...

**Comment by yogeshbdeshpande** [comment]
The issue is the text above intends to describe how Verifier internally should collect all the measurements pertaining to the same `environment`   coming from a sea of triples within CoRIM.

However the text above indicates the opposite!

**Comment by yogeshbdeshpande** [comment]
Closing as Andy has addressed this using PR #193
