### ISSUE TITLE
crypto-key as instance environment identifier

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#146]
`environment-map` supports class, instance and group identifiers. Instance identifiers can be UUID or UEID. 

A PRoT use case can use key-id to identify components by their key. 
A PRoT may dynamically discover "platform" devices (either via hot-plug or by rebooting). The PRoT can perform local security checks (or not) and report discover of the device(s) to a remote Verifier. 

The CoMID schema can represent information about the device by identifying it using its key. For example, it may have a DICE device or alias key. 

However, the current definition of `instance` in `environment-map` doesn't allow keys as identifiers. This can be fixed by:
```
$instance-id-type-choice /= $crypto-key-type-choice
```
`$crypto-key-type-choice` is already a CBOR tagged value.

**Comment by henkbirkholz** [comment]
PRoT: Platform Root of Trust

**Comment by henkbirkholz** [comment]
Key material unique to an environment can of course be used to identify the environment. Both an external kid as well as a pub key in cases of pub/priv key pairs can be used to identify an environment, correspondingly. As long as the security considerations are clear and identification via key material does not come with unwanted side effects, that should be okay?

**Comment by henkbirkholz** [comment]
Are "platform" devices simply (modular) device components, such as a NIC?

**Comment by nedmsmith** [comment]
> Are "platform" devices simply (modular) device components, such as a NIC?

Could be, the lead Attester determines which components of the platform are grouped together as part of a session with a Verifier.

**Comment by yogeshbdeshpande** [comment]
Closing the issue as PR #151 has been merged!
