### ISSUE TITLE
Should we allow class Conditional Endorsements to match instance measurements?

### ISSUE THREAD

**Issue by andrew-draper** [ietf-rats-wg/draft-ietf-rats-corim#172]
If an attester includes an instance identifier in the evidence it provides then the current matching rules will prevent a triples in a class CoMID from matching against that measurement.

For example, a measurement might have the following value:

```cbor-diag
  [
    / environment-map / {
      / comid.class / 0 : {
        / comid.class-id / 0 : / 2.16.1.2.3.4 / 111(h'6001020304'),
        / comid.vendor / 1 : "example.com"
      }
      / comid.instance / 1 : #6.558 / COSE_Key / [ / TODO-insert-key-here / ]
    },
    / measurement-map / {
      / comid.mval / 1 : {
        / comid.digests / 2 : [
          [
            / sha-384 / 7,
            h'15E77D6F133252F1DB7044901313884F2977D2109B33C79F33E079BFC78865255C0FB733C240FDDA544B8215D7B8F815'
          ]
        ]
      }
    }
  ], 
```
The current matching rules do not let this match against the following reference value (for example in a Conditional Endorsement Triple, or in other forms of conditional endorsement).
```cbor-diag
  [
    / environment-map / {
      / comid.class / 0 : {
        / comid.class-id / 0 : / 2.16.1.2.3.4 / 111(h'6001020304'),
        / comid.vendor / 1 : "example.com"
      }
    },
    / measurement-map / {
      / comid.mval / 1 : {
        / comid.digests / 2 : [
          [
            / sha-384 / 7,
            h'15E77D6F133252F1DB7044901313884F2977D2109B33C79F33E079BFC78865255C0FB733C240FDDA544B8215D7B8F815'
          ]
        ]
      }
    }
  ], 
```
The missing instance value prevents the triple from matching.

Adding instance identifiers to the reported evidence is useful as it lets the verifier handle cases where it is evaluating the a state which contains multiple TEs of the same type (which may be in the same state or in slightly different states).

Class Conditional Endorsements are a key part of the semantics of CoMID files. We need a way to apply a class conditional endorsement to evidence or endorsements which include instance  identifiers.

I think this can be done with a few small changes to the text, and I will make a proposal if nobody objects to the idea.

**Comment by nedmsmith** [comment]
When we defined environment-map, there was an expectation that one of the 3 forms of measurement-map identifiers would be used. It was more of an artifact of CDDL that permitted multiple forms could be used simultaneously (at least that is how I remembered it).
However, using multiple forms could enable interesting use cases such as the one Andy describes (i.e. AE dynamically discovers / reports a composition of components that didn't exist at time of manufacture). The instance-id is a convenient way for the AE to disambiguate multiplicity in evidence.

There is a more general conversation around what it might mean to populate multiple forms of environment-map in ref vals / endorsements. For example, if an environment is identified by instance-id, but there are relevant class attributes (e.g., vendor, model). Would it make sense to allow this? If so, would it make sense to match evidence using both instance-id and class-map, or should matching on instance-id only be permitted (and treat the class-map attributes as measurements)?
