### ISSUE TITLE
Tagged bytes as instance and class identifiers

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#184]
Recently, there has been a discussion on the RATS mailing list about using [SEV-SNP CHIP_ID](https://mailarchive.ietf.org/arch/msg/rats/NdvOUhPp8t4dG8fI0YKNK-H_M1w/) as an AE instance identifier. This same requirement had previously arisen in a SEV-SNP integration with Veraison.
Additionally, there are internal discussions at Arm regarding CCA workload identification, which cannot use the currently defined type choice.

Extending the class and instance identifier types with an opaque byte array whose exact semantics would be defined by the CoRIM profile could address both cases, among others.

```cddl
$tagged-bytes-type = #6.TBD(bytes)

$instance-id-type-choice /= $tagged-bytes-type
$class-id-type-choice /= $tagged-bytes-type
```

**Comment by yogeshbdeshpande** [comment]
Yes, we discussed this internally and felt that this is very much required for individual vendors to have the flexibility of defining the required semantics of free expression of Identities.

**Comment by deeglaze** [comment]
Tagged bytes composed with an AMD SEV-SNP profile identifier seems adequate to interpret this as CHIP_ID. LGTM.
