### ISSUE TITLE
PCR bank measurement type

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#185]
Some environments (e.g., Arm CCA realms, TPMs) have a bunch of measurements bundled in PCR banks rather than single digests.

Instead of having each technology provide their own custom PCR-bank measurement type, we should define it as a basic, reusable CoMID type.

For example - modelled on the `digest` type:

```cddl
; design A

pcrs = [
  alg:  (int / text)
  slots: [ + bytes / nil ]
]
```

The `nil` alternative is for when the PCR slot is not populated or match is to be skipped.

CoRIM profiles will have to define the exact shape of the bank, i.e., the number of elements in the `slots` array.

**Comment by yogeshbdeshpande** [comment]
In my view if we provide per digest slot as below to express it like this:

digest-meta-type-choice = int ; example PCR Index
digest-meta-type-choice = text ; example "REM Bank 0"

digests = [
  ? meta: $digest-meta-type-choice
  alg:  (int / text)
  vals: [ + bytes ]
]

**Comment by thomas-fossati** [comment]
The difference is that in design A the slot index is implicit, while in design B it's explicit.

So, a PCR bank with 4 slots, where only 0, 2 and 3 are populated, would be encoded as:

* design A:
 
```cbor-diag
[
  / alg /   "my-hash-algorithm",
  / slots / [ h'00', nil, h'22', h'33' ]
]
```

* design B:

```cbor-diag
[
  / alg /   "my-hash-algorithm",
  / slots / [ [ 0, h'00' ], [ 2, h'22' ], [ 3, h'33' ] ]
]
```

**Comment by nedmsmith** [comment]
Other roots of trust can make use of an integrity register (aka PCR) structure. Allowing the "slot" to have a text name as well as a numeric value provides better flexibility for non-TPM IR designs. This (int / text) is not unlike the cmw collection approach.

**Comment by thomas-fossati** [comment]
> Other roots of trust can make use of an integrity register (aka PCR) structure.

Can you provide examples?

> Allowing the "slot" to have a text name as well as a numeric value provides better flexibility for non-TPM IR designs.

You mean:

```cddl
pcrs = [
  alg:  (int / text)
  slots: {
    + (int / text) => bytes
  }
]
```

or

```
pcrs = [
  alg:  (int / text)
  slots: [ + [ index: uint, value: bytes, ? name: text ] ])
]
```

**Comment by nedmsmith** [comment]
This is what I was thinking:
```
pcrs = [
  alg:  (int / text)
  slot: {
    + (int / text) => bytes
  }
]
```
Note: I think it is a singleton slot.

**Comment by thomas-fossati** [comment]
> This is what I was thinking:
> 
> ```
> pcrs = [
>   alg:  (int / text)
>   slot: {
>     + (int / text) => bytes
>   }
> ]
> ```

OK.  However, I'd like to see at least one example that justifies using the text label.

> Note: I think it is a singleton slot.

Hmm. if it's defined as:

```
{ + (int / text) => bytes }
```

i.e. a map of one or more elements, the plural seems warranted, no?

**Comment by thomas-fossati** [comment]
Besides, in general, are `text` and `int` keys allowed within the same map?  Or is that profile-specific?

(PS: `int` should be `uint`, I guess?)

**Comment by nedmsmith** [comment]
+1 uint

**Comment by deeglaze** [comment]
Where do you plan on this pcr measurement type being? `$$measurement-values-map-extension //= &(&(pcrs: 13) => pcr-bank-map)`?

I'm rather perplexed at the contended global number space for measurement-values-map as opposed to `&(uri-profiles: ??) => uri-measurement-values-map` for niche environments to provide their profile and extensions through a URI they control bound to a map of values of any kind they want. This is generally more extensible in the way in-toto allows folks to use URIs for predicates and for assigning evaluators.

PCRs and their behavior in CoRIM are best specified by the TCG in their own referenced URI for the TPM 2.0 profile, rather than tunneled through CoRIM standards folks as its own first class model, no?

**Comment by thomas-fossati** [comment]
> Tpm2 uses multiple algorithms and digests per PCR similar semantics as CoRIM digests measurement.

Question: in TPM2 once an algorithm is set it's used for all PCRs?  Or could one have PCR[i] with alg X and PCR[j] with alg Y simultaneously?

**Comment by thomas-fossati** [comment]
> Where do you plan on this pcr measurement type being? `$$measurement-values-map-extension //= &(&(pcrs: 13) => pcr-bank-map)`?
> 
> I'm rather perplexed at the contended global number space for measurement-values-map as opposed to `&(uri-profiles: ??) => uri-measurement-values-map` for niche environments to provide their profile and extensions through a URI they control bound to a map of values of any kind they want. This is generally more extensible in the way in-toto allows folks to use URIs for predicates and for assigning evaluators.
> 
> PCRs and their behavior in CoRIM are best specified by the TCG in their own referenced URI for the TPM 2.0 profile, rather than tunneled through CoRIM standards folks as its own first class model, no?

I quite agree.

At the same time, for types that are shared across different use cases, it makes sense to have them represented as first-class CoRIM types that different profiles can reuse.

In any case, the two approaches are not mutually exclusive.

**Comment by henkbirkholz** [comment]
Maybe a minor detail:

Is everybody aware that a PCR `bank` allows for various algs used? You can request different digests using different alg-ids representing the same measured ("extended") operational state. As a point of reference, I scraped some old CDDL excerpts for the TPM TSS (based on ; TCG TPM Structures, Family 2.0, Level 00, Rev 01.38, Sep 29, 2016):

```
; Hash/Digest Structures (10.3)
TPMT_HA = { TPMU_HA-hashAlg,
            TPMU_HA-digest,
          }

TPMU_HA-hashAlg = (hashAlg: TPMI_ALG_HASH)
TPMU_HA-digest = (digest: TPMU_HA)
TPML_DIGEST_VALUES-digests = (digests: [*TPMT_HA])
```
TPMI_ALG_HASH is the subsets of hash-ids from the TCG Algorithm Registry.

**Comment by thomas-fossati** [comment]
Taking Ned's input about TPM2 into account, and after a chat with Henk about that, this looks like a sensible design:

```
pcr-id = uint

pcrs = {
  + pcr-id => [ + digest ]
}

; digest is already defined in CoRIM as:
digest = [
  alg: (int / text),
  val: bytes
]
```

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati As I was suggesting the design to be on the similar lines that what Ned stated;
' Allowing the "slot" to have a text name'

If I see the suggested last proposed changes from you, that aspect is missing.

Did you mean :
pcr-id = uint /text?

**Comment by thomas-fossati** [comment]
> Allowing the "slot" to have a text name

Maybe.  I still haven't gotten an answer from Ned regarding:

> Can you provide examples? All the cases we are factoring in (i.e., TPMs / vTPMs, CCA Realm REMs) have the standard TPM structure (slot[i] => bytes).

**Comment by yogeshbdeshpande** [comment]
Also, I suggest two improvements:

We should not call it PCR (as in some cases, it may not be strictly Platform Configuration Registers, like the case of ARM CCA, where they are Workload Measurement Set) 
Also PCR is a term `heavily` only used and directed to TPM Measurements.

I suggest we call it as:
env_digests
OR
digest_bank

**Comment by thomas-fossati** [comment]
> Also, I suggest two improvements:
> 
> We should not call it PCR (as in some cases, it may not be strictly Platform Configuration Registers, like the case of ARM CCA, where they are Workload Measurement Set) Also PCR is a term `heavily` only used and directed to TPM Measurements.
> 
> I suggest we call it as: env_digests OR digest_bank

PCR semantics (i.e., set of registers which are _"extended"_) is well understood and is applicable beyond the TPM scope.  I don't think the names you propose would be an improvement.

**Comment by yogeshbdeshpande** [comment]
PCR name itself expands to `Platform Configuration Registers` which restricts it only to Platforms.

**Comment by yogeshbdeshpande** [comment]
To be super clear, I want to confirm, what is our overall proposal:


1. ` measurement-values-map = non-empty<{
 ? &(digest-bank: 14) => [+env-digests]
}

env-digests = {
  digest-id => [+digest]
}` 

OR

2. I suppose we meant the below:

` measurement-values-map = non-empty<{
?  &(digest-bank: 14) => env-digests
}

env-digests = [
+ { digest-id => [+digest] }
] `

**Comment by thomas-fossati** [comment]
> [...] what is our overall proposal:

```
pcr-id = uint

pcrs = {
  + pcr-id => [ + digest ]
}

; digest is already defined in CoRIM as:
digest = [
  alg: (int / text),
  val: bytes
]

$$measurement-values-map-extension //= (
  &(pcrs: TBD) => pcrs
)
```

**Comment by nedmsmith** [comment]
> > Allowing the "slot" to have a text name
> 
> Maybe. I still haven't gotten an answer from Ned regarding:
> 
> > Can you provide examples? All the cases we are factoring in (i.e., TPMs / vTPMs, CCA Realm REMs) have the standard TPM structure (slot[i] => bytes).

There are non-TPM cases that use "Integrity Registers" such as Intel AMT. The AMT subsystem updates an IR that is read by system SW. It is simply the "AMT IR" rather than IR[0]. 

The TPM NV can be used as a PCR. The NV location is its name. 

TCG DPE (DICE Protection Environment) can maintain a set of TCI values that are known by their name rather than an array of TCI values. I'm aware of one DPE implementation that treats the TCI as an IR / "extend" register. 

The `pcr` naming is biased toward TPM PCR use cases. 

In CoRIM, the `pcr` measurement type is only one part of a triple. The triple environment may provide additional context for disambiguating the measurement. For example, a class-map could use `index` to describe an array of TPM PCR locations and `digests` could be used directly without additional qualification.

A different `class-id` could model TPM NV and `index` models offsets within TPM NV that are used for integrity registers.

If `pcrs` is aimed exclusively at TPM PCRs, then should corim also define `tpm-nv-irs`, 'dice-tcis`, and `iamt-ir` variants?

**Comment by thomas-fossati** [comment]
Cool, thanks @nedmsmith.  I like "Integrity Registers" rather than PCR.  I will update the example CDDL above accordingly.

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati 

I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1

should be:

```
integrity-register-id = uint / text

integrity-registers = [
  + integrity-register-id => [ + digest ]
]

; digest is already defined in CoRIM as:
digest = [
  alg: (int / text),
  val: bytes
]

$$measurement-values-map-extension //= (
  &(integrity-registers: TBD) => integrity-registers
)

```

**Comment by thomas-fossati** [comment]
> I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1

@yogeshbdeshpande: nope.  We want a map, not a record.

**Comment by yogeshbdeshpande** [comment]
> > I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1
> 
> @yogeshbdeshpande: nope. We want a map, not a record.

Then where is the `multiplicity` of Per slot index?

**Comment by thomas-fossati** [comment]
> > > I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1
> > 
> > 
> > @yogeshbdeshpande: nope. We want a map, not a record.
> 
> Then where is the `multiplicity` of Per slot index?

IIUC your question, it's here:
```
 [ + digest ]
```

**Comment by yogeshbdeshpande** [comment]
> > > > I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1
> > > 
> > > 
> > > @yogeshbdeshpande: nope. We want a map, not a record.
> > 
> > 
> > Then where is the `multiplicity` of Per slot index?
> 
> IIUC your question, it's here:
> 
> ```
>  [ + digest ]
> ```

No that is per slot digest, so If I have PCR index 0, then I will put integrity-register-id = 0 and Digest for `0` around that.

But I want to make this for other PCR Indexes also, where is that array expression, which is required ?

**Comment by thomas-fossati** [comment]
> > > > > I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1
> > > > 
> > > > 
> > > > @yogeshbdeshpande: nope. We want a map, not a record.
> > > 
> > > 
> > > Then where is the `multiplicity` of Per slot index?
> > 
> > 
> > IIUC your question, it's here:
> > ```
> >  [ + digest ]
> > ```
> 
> No that is per slot digest, so If I have PCR index 0, then I will put integrity-register-id = 0 and Digest for `0` around that.
> 
> But I want to make this for other PCR Indexes also, where is that array expression, which is required ?

here:
```
+ integrity-register-id => ...
```

**Comment by yogeshbdeshpande** [comment]
> > > > > > I think the correct CDDL as per https://datatracker.ietf.org/doc/html/rfc8610#section-3.5.1
> > > > > 
> > > > > 
> > > > > @yogeshbdeshpande: nope. We want a map, not a record.
> > > > 
> > > > 
> > > > Then where is the `multiplicity` of Per slot index?
> > > 
> > > 
> > > IIUC your question, it's here:
> > > ```
> > >  [ + digest ]
> > > ```
> > 
> > 
> > No that is per slot digest, so If I have PCR index 0, then I will put integrity-register-id = 0 and Digest for `0` around that.
> > But I want to make this for other PCR Indexes also, where is that array expression, which is required ?
> 
> here:
> 
> ```
> + integrity-register-id => ...
> ```

My question is : Can we do this in a `map` + expression ? I thought this is for `arrays` ?

**Comment by thomas-fossati** [comment]
> My question is : Can we do this in a `map` + expression ?

yes

**Comment by yogeshbdeshpande** [comment]
Thanks. Just wanted to confirm, then is the positional order in the multiplicity always is preserved in this or not?

**Comment by thomas-fossati** [comment]
> [...] is the positional order in the multiplicity always is preserved in this or not?

why would it be relevant?

**Comment by deeglaze** [comment]
Given that the conversation about extensibility is to prefer cleaner separation into namespaces apart from what is already stuck for DICE, I think we should revisit refactoring this into a type that's associated with a trustedcomputinggroup.org url base for the type. Similarly I don't think PCR banks are the whole story, given that folks may want to have more inspection on the event log entries instead, and just keep the PCR bank as a final integrity test for evidence appraisal.

**Comment by nedmsmith** [comment]
Do you have a specific suggestion for what should change (as this has been merged already i think)?

**Comment by deeglaze** [comment]
measurement-values-map has the possibility of extensions that are protected by this standards body, and everything that already exists is there for DICE's benefit.
I don't think that anything else should be added other than a namespaced entry with payload schema entirely determined by the namespace.

```
  ? &(named-extensions: 14) => [ + $named-extension ]

$named-extension-map = [
  $profile-type-choice
  bytes
]
```

The TCG should use its own OID for TPM 2.0, say, to allow the bytes to be interpreted as an CBOR encoding of a map that includes something with the same schema as the proposed integrity-registers CDDL.

**Comment by thomas-fossati** [comment]
hi @deeglaze, the scope of this is larger than PCRs.  It's an attempt at creating a CoRIM base type that covers TPMs, vTPMs as well as other types of "integrity registers" - for example, Arm CCA Realm's REMs.
