### ISSUE TITLE
measurement-values-map code point 12 already in use

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#186]
The concise-evidence schema defined in TCG DICE Concise Evidence Binding for SPDM already assigns code point 12 to spdm-indirect. 

  ? &(cryptokeys: 12) => [ + $crypto-key-type-choice ] should move to 13.
```
  ? &(cryptokeys: 13) => [ + $crypto-key-type-choice ]
```

**Comment by andrew-draper** [comment]
This change has been made. Is it ok to close the issue?

**Comment by nedmsmith** [comment]
yes.

**Comment by nedmsmith** [comment]
Fixed in main.
