### ISSUE TITLE
Provide a CDDL definition of SW Update Flow

### ISSUE THREAD

**Issue by yogeshbdeshpande** [ietf-rats-wg/draft-ietf-rats-corim#21]
Currently the existing CoRIM schema does not lend itself to natural expression for Providing Endorsements for SW updates.

This issue tracks the further work required in this area!

**Comment by yogeshbdeshpande** [comment]
Here is the proposed flow:

1) Each Measured Component/Layer within the device can has its Reference Values Expressed in a Reference Triple Record as below:

; REFERENCE-VALUE triple
; "target environment $TE" "has reference measurements" "$RV"
reference-triple-record = [
  environment-map ; target environment
  [ + measurement-map ] ; reference measurements
]

; Here "Target Environment is the Identifier for the Reference Measurements"

2) A Device is composed of a set of Components/layers which is expressed with Domain Composition Triples

; DOMAIN-MEMBERSHIP-TRIPLE-RECORD
; Predicate: $TD Target domain has member environment(s) $EV

$$triples-map-extension //= ( 
comid.domain-membership-triples => domain-membership-triple-record 
)
comid.domain-membership-triples = 5

domain-membership-triple-record = [
 $domain-type-choice, [ + environment-map ]
]


3) When a Device Component/layer has a SW Update: It first pushes a new REFERENCE VALUE Triple Record, as below:

; REFERENCE-VALUE triple
; "target environment $TE" "has reference measurements" "$RV"
reference-triple-record = [
  environment-map ; target environment
  [ + measurement-map ] ; reference measurements
]


4) Then it pushes a new Update Triple Record which associates new Environment to the Old Environment.
$$triples-map-extension //= ( 
comid.environment-update-triples => environment-update-triple-record 
)

comid.environment-update-triples = 6

; "target environment $TE" updates one or more existing environments.
environment-update-triple-record  = [
environment-map ; target environment
 [ +environment-map   ]
]

6) After a successful Update in 5 a new Domain Composition Triple will establish a new linkage!

**Comment by yogeshbdeshpande** [comment]
Possibly user can use the Ref Triple with same Env ID and different Measurements, and update it to Verifier
Then use the Updates Triple with same Env ID in both target and source

**Comment by nedmsmith** [comment]
There is potentially a 'CRUD' lifecycle consideration for each structure described by CoRIM (e.g., RIM, tag, domain, environment, measurement and triple). An "update" potentially could change any of these structures. It makes sense to describe updates in terms of CRUD semantics for each statement in the schema. Maybe only C and D are valid lifecycle considerations? Given U semantics means 'changes' rather than 'adds', an "update" might include any of C, U and D for a given statement. 

Maybe this suggestion exceeds the scope of this issue, but maybe there should be separate issues created for each statement type in CoRIM that considers CRUD semantics? Then this issue could address mapping an "update" to the various places within CoRIM that define CRUD semantics.

**Comment by nedmsmith** [comment]
It should be possible to update a component and corresponding measurement without rolling class-id. The class-id may describe the component's long-lived (strawman) relationship to other components. The strawman definition should not be forced to change every time a measurement value changes. In this use case, different class-map identifiers are essentially aliases for the original. Aliases indicate that some sort of measurement change occurred, but greater analysis is needed to determine if substantive change to the strawman definition of the component has not changed. Another reason to allow 'alias' class-maps is the way an organization manages class identifiers could change over time moving from say ('vendor', 'model', 'index') to ('class-id'=UUID) or ('class-id'=OID). These are alias changes that don't affect the strawman definition.

Allowing the strawman to change is also a valid use case. If it is determined that the strawman should add / remove a feature (e.g., add a finger or remove a finger). Then a new class-map value indicates an addition, removal of a class-map value indicates deletion. It is important that this type of addition/deletion isn't confused with the above paragraph alias use case.

**Comment by yogeshbdeshpande** [comment]
The proposed solution above is aligned with the core principles laid down in Attestation Architecture.

A domain has Multiple Environments  - identified uniquely by Environment Identifiers ( Example Class Id)
It is the individual Environments which are measured by a set of Reference Values and Endorsed Values

For a particular Environment, Say `Env-X` A particular Reference Value may Change. Stated Alternatively for a Reference Value Identified by a Id, the value of Reference may change. 

The new approach approach solves the issue identified in the earlier solution (Stated at the top of the issue), where each measurement is associated with Id identified as Environment. Thus each time a measurement changes, will introduce a new Environment ID, which is unsustainable, as highlighted below:
 _The class-id may describe the component's long-lived (strawman) relationship to other components. The strawman definition should not be forced to change every time a measurement value changes_

**Comment by thomas-fossati** [comment]
a bunch of fly-by comments

> $identifier-type-choice /= tstr $identifier-type-choice /= "reference-value" $identifier-type-choice /= "endorsed-value"

these could/should be numeric identifiers

> ; it is expected that when the user uses this map ; in the subject environment map needs to be present identifier-map = non-empty<{ &(type:0) => $identifier-type-choice ? &(env: 1) => environment-map &(mkey : 2) ==> $measured-element-type-choice }>

using the term "identifier" has very little meaning, identifier of what exactly?

> ; for a given supply chain entity an identifier updates one or more identifiers ; if this triple record is not supplied in a CoRIM then it is assumed that the ; newly added reference or endorsed value (via reference-triple-record/endorsed-triple-record) ; Has an Update path to any other ref/end value in the Verifier.
> 
> ; The triple below sets the relationship explicitly update-triple-record = [ identifier-map [+ identifier-map] ]
> 
> ============================================================================== ; explicit removal of old reference values or endorsed values blacklist-triple-record = non-empty<{ environment-map [+ identifier-map] }

you haven't followed the "terminology" thread in the IETF :-)

**Comment by yogeshbdeshpande** [comment]
> terminology

using the term "identifier" has very little meaning, identifier of what exactly?
One has to unpack the identifier-map to understand for what this identifier belongs to:

It is the identifier type ==> that establishes the identifier name, it could be either the reference-value or endorsed-value
And the Environment and Measurement Identity completes its value

**Comment by thomas-fossati** [comment]
> One has to unpack the identifier-map to understand for what this identifier belongs to:
> It is the identifier type ==> that establishes the identifier name, it could be either the reference-value or endorsed-value
> And the Environment and Measurement Identity completes its value

measurement identifier then?

**Comment by thomas-fossati** [comment]
```
identifier-map = non-empty<{
  &(type:0) => $identifier-type-choice
  ? &(env: 1) => environment-map
  &(mkey : 2) ==> $measured-element-type-choice
}>
```

is a stray/unqualified mkey ok?

**Comment by yogeshbdeshpande** [comment]
> > One has to unpack the identifier-map to understand for what this identifier belongs to:
> > It is the identifier type ==> that establishes the identifier name, it could be either the reference-value or endorsed-value
> > And the Environment and Measurement Identity completes its value
> 
> measurement identifier then?

ok, we can think of a name that is applicable to both ref values and endorsed values

**Comment by yogeshbdeshpande** [comment]
> ```
> identifier-map = non-empty<{
>   &(type:0) => $identifier-type-choice
>   ? &(env: 1) => environment-map
>   &(mkey : 2) ==> $measured-element-type-choice
> }>
> ```
> 
> is a stray/unqualified mkey ok?

Not sure I fully understood the question?

It is expected that the Supply Chain entity will use the same `mkey`  that it used to provision the updated ref-val or end-val

**Comment by thomas-fossati** [comment]
> > ```
> > identifier-map = non-empty<{
> >   &(type:0) => $identifier-type-choice
> >   ? &(env: 1) => environment-map
> >   &(mkey : 2) ==> $measured-element-type-choice
> > }>
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > is a stray/unqualified mkey ok?
> 
> Not sure I fully understood the question?

I meant: `env` being optional it seems you want to allow `mkey`s that are not anchored onto a parent environment.

**Comment by yogeshbdeshpande** [comment]
Ah now I got the point. Thanks. Yes, I wanted to make the Env-map mandatory! Happy to do that in fact!
But when the new update id updates many id's on th right then Env-map becomes repetitive which is a slight distraction.

And I do not want to have many more maps, so this is a dilemma

Happy to make it mandatory!

**Comment by thomas-fossati** [comment]
This has now morphed into the x- triples discussion (see #32)
