### ISSUE TITLE
Delegate "validity" to signing key certificates

### ISSUE THREAD

**Issue by deeglaze** [ietf-rats-wg/draft-ietf-rats-corim#222]
We should remove `validity-map` entirely. The validity of a signature is the purview of the PKI only. Validity without a signature is irrelevant.

**Comment by thomas-fossati** [comment]
Absent a way to revoke a certain CoRIM, we must have a mechanism to timebomb it.

That mechanism is the validity-map.

(Even if an explicit revocation mechanism existed, the timebomb is also a useful defense.)

**Comment by thomas-fossati** [comment]
Clarifying question: Is the proposal to require the supply chain to mint a one-shot, short-term certificate for every CoRIM?

**Comment by deeglaze** [comment]
Not necessarily every CoRIM, but perhaps with every CoRIM bundle created for a release, yes. This is common practice for code signing.

**Comment by deeglaze** [comment]
Alternatively, whatever notion of validity a profile wants can be added later. There really should be a core and extended form of CoRIM for all these bells and whistles.

**Comment by thomas-fossati** [comment]
> Alternatively, whatever notion of validity a profile wants can be added later. There really should be a core and extended form of CoRIM for all these bells and whistles.

I think that the lifetime of the information asserted in a CoRIM is a basic feature and should be provided (at least in some crude form) by the base spec.

**Comment by deeglaze** [comment]
Okay, can we say this issue is to move validity-map and uses to a Lifetime management section to discuss its use? It seems there is no removing anything at this point, but we can at least give interpretations as meant by the default (DICE) profile.
