### ISSUE TITLE
Endorsements are implicitly conditional on reference values. Which ones?

### ISSUE THREAD

**Issue by deeglaze** [ietf-rats-wg/draft-ietf-rats-corim#251]
> An Endorsed Values triple declares additional measurements that are valid when a Target Environment has been verified against reference measurements.

There can be multiple reference measurements that are signed for a certain class-id. I don't expect reference measurements to be signed as limited to any specific instance. It doesn't seem correct to just accept anything from the `authorized-by`. The only interpretation that I can think of that could work is if the endorsement triple's environment is also associated with a reference-value-triple in the same CoMID, and that reference value has been added to the ACS.

The 1 environment to identify the reference values doesn't apply to the conditional-endorsement-triple now though, so I'm guessing those _aren't_ implicitly conditional on the reference values? I'd really like if we could solidify the semantics by giving explicit transformations of triples in CoRIM to the relations that have more explicitly defined semantics?

> Evidence is divided up into one or more `ev` relations where the condition ECT identifies the Attester from which Evidence was collected. If the Verifier maintains multiple Attester sessions, the Verifier session may be identified using an ECT.

Is this "Evidence is" meant to be "Endorsements are"? The `ev` relation is for endorsements.

> Evidence information is mapped to an addition ECT that populates each of the ECT fields.

This seems more correct, but by saying `addition` instead of the `ae` relation doesn't match the use of relation in the previous sentence.

**Comment by nedmsmith** [comment]
Has this issue been addressed?

**Comment by deeglaze** [comment]
Yes, we changed the wording to not imply any measurement condition.
