### ISSUE TITLE
Claim naming, data types and matching rules

### ISSUE THREAD

**Issue by andrew-draper** [ietf-rats-wg/draft-ietf-rats-corim#253]
An Attesting Environment creates claims about a Target Environment which are processed and added to the Attestation Claim Set. These claims are later matched against reference values from CoMIDs.

For this issue, I am defining a claim as including:
- a name indicating what was measured
- the value of the measurement
- authority information about the measurement
There may be other information associated with the claim, but it is not relevant to this issue.

In some cases, each environment contains a single claim, or a single claim of each type, and the matching rules for that type are acceptable. For example if there is one digest claim and one raw value claim in an environment). This case is easy to encode within the reference claims. I will call these "standard claims".

In other cases, extensions are required. In this issue I will use the name "extension claim" for a claim which cannot be encoded using the standard fields within `measurement-values-map` (perhaps renamed to `claims-map`). 

Uses for extension claims may include:
1. multiple claims with the same data-type in the same environment
2. claims whose semantics cannot be easily represented by the standard data types
3. claims which require custom matching rules

The current text suggests that for each of these uses, negative labels within `measurement-values-map`  can be used as part of the solution.

For each extension claim, the verifier and/or relying party needs to know three things:
- Its name, that is what was measured to generate the claim
  - For the verifier, environment maps are opaque.
  - CoRIM authors and relying parties understand what names are
- How the data is represented within the claim
  - The verifier can sometimes treat this as opaque
- How to import and export the claim
- How to compare the claim data against a reference value
  - There may be multiple comparison options for the same data

Import, export and comparison operations for extension claims with new data types will normally require custom code in the verifier. This is to be expected, especially for legacy data whose semantics are already established.

Should we design CoMID so that it is easy to add some extension claims without having to write significant code in the verifier?

I assume that import of extension claims will be handled by the document which describes import of values into the ACS, so that is not a problem for us to consider here. We can similarly defer consideration of export until later.

We do need to consider comparison of extension claims here, as that affects the syntax of reference values etc. in CoRIM files.

To me, the key issue is how the verifier determines the data type of a CoRIM file. The data type will be an internal identifier which triggers appropriate code for matching, serialization, etc.

The data type of standard claims is determined from the `measurement-values-map` index.

Most data types have a single matching rule which triggers code which will match an ACS claim against the corresponding reference value.

Some data types, for example `svn`, have multiple data matching rules. The type of matching is chosen by a CBOR TAG on the reference value (specifically, on the value within the `measurement-values-map`).

For extension claims, how should the verifier determine the data type and the matching rules to be used when matching a reference value against that claim?

We have discussed several options for selecting data type and matching rules. The fields which we have discussed using to select include:
- CoRIM profile (of the CoRIM which contains the reference value)
- All fields in the `environment-map`
- The `class` field within `environment-map`
- The `measurement-value-map` label
- The CBOR TAG on the reference value being measured
- Are there any others?

Which of these should be used?

Is it worth adding a way to add extension claims without requiring new code in the verifier?

For example, a profile could describe an encoding and a set of matching rules for a data type. Implementing this will require new code in the verifier. An imported claim and/or a reference value could then indicate that the claim with a particular `environment-map`/`class` and `measurement-value-map` label uses the defined data type.

If this is worthwhile then how should this be encoded in CoRIM files and in internal data structures?

If so then how should the data type be encoded?

**Comment by deeglaze** [comment]
All extensions are determined by the profile, so you'll dispatch from profile id to typeclass instance (or whathaveyou) to implement matching for the extensions and restrictions for standard fields.

> Should we design CoMID so that it is easy to add some extension claims without having to write significant code in the verifier?

No, since that bleeds into becoming a full programming language.

**Comment by deeglaze** [comment]
Note that my proposed text about tagging data types having a "default" comparison method can perhaps work for a lot of profiles, so you can map multiple profile ids to "use default semantics" for extensions' measurement-values-map extensions. That doesn't eliminate the choice that some profiles may make to specify alternative matching semantics for their extensions.

**Comment by andrew-draper** [comment]
We discussed this in the CoRIM meeting on 14th August.

The feeling of the meeting is that every ACS entry may include a profile identifier.
If the ACS entry includes non-standard data types then it must include a profile identifier (if it does not then its not valid).

A verifier will need to include code for every supported profile, there will be no way to support custom data types without writing code.
The profile definition must describe data formats, serialization and matching rules for the data types which it defines.

Multiplicity of data types is important - for example multiple SVNs within the same environment. The `integrity-registers` data type supports a multiplicity of `digest` data values, but this is a special case. We would like a standard way to represent the multiplicity of all data types.

Yogesh will open a new issue to discuss the syntax and matching rules for multiplicity of data types.
