### ISSUE TITLE
Define or remove `offline`

### ISSUE THREAD

**Issue by steven-bellock** [ietf-rats-wg/draft-ietf-rats-corim#271]
The specification talks about `offline` verification of keys. For example
>The Verifier SHOULD perform offline verification of keys contained in Device Identity triples.

I'm not sure what `offline` means here. Either `offline` should be defined, or it can probably be removed since
>The Verifier SHOULD perform verification of keys contained in Device Identity triples.

sounds good to me.

**Comment by nedmsmith** [comment]
see PR #274 

Offline refers to checks that can't be performed by an attesting environment in the context of collecting measurements. For example, an AE could do proof-of-possession on the TE that wields a key. Removing the term makes sense there isn't industry consensus that offline refers to key verification sans PoP.
