### ISSUE TITLE
Change sec-match-one-se to be matching one ECT to another.

### ISSUE THREAD

**Issue by deeglaze** [ietf-rats-wg/draft-ietf-rats-corim#279]
We have matching semantics sometimes in terms of external representation, and sometimes internal representation.

The translation from external triples to internal relations like `rv` is incomplete in the definition of the semantics. The crux of the representation is matching an ECT condition against an ECT in the ACS.

**Comment by deeglaze** [comment]
I recommend that we name the condition ECT the "pattern" and the ACS entry against which to match, the "entry".

**Comment by deeglaze** [comment]
I suppose not. I have a bigger follow-up to this suggestion though to use ordering sequents as an initial definition to start writing the prose.

**Comment by nedmsmith** [comment]
> ordering sequents

Are you suggesting that a reader of this spec needs to have a working knowledge of formal logics in order to understand this spec?

**Comment by deeglaze** [comment]
No, I'm saying I'm summarizing my semantics in relationships in a comment here to help folks understand my intention behind the prose to come, since it's very technical.

**Comment by deeglaze** [comment]
To get roughly on the same page before writing the prose, here's my interpretation as a mathematical relation.

I'll treat `? x : cddl` to mean `x: optional<encodeType(cddl)>`.

```
p  ⊢ ce <= ee : optional<environment-map>
p  ⊢ cc <= ec : optional<[ + local-claim]>
p  ⊢ ca <= ea: optional<[ + $crypto-key-type-choice ]>
 ⊢ ccm <= ecm : optional<cm-type>
-------------------------------------------------- [ ECT matching ]
 ⊢ { ce cc ca ns ccm p } <= { ee ec ea ns ecm p }
```

Note `ns` and 'p' on both sides on the bottom to require exact equality for namespace and profile whether given or not.

For optional type ordering, we treat `none` as logical bottom:

```
-------------- [ optional<T> refl ]
 ⊢ none <= none : optional<T>

--------------- [ optional<T> bottom ]
 ⊢ none <= some v : T

P ⊢ v0 <= v1 : T
--------------------- [ optional<T> <= ]
P ⊢ some v0 <= some v1 : optional<T>
```
Relations can be refined by the profile or not. The P context can be empty or a profile identifier.


cm-type, bstr, uint, and tstr have no extra structure to match.
```
----- [cm-type refl ]
P ⊢ x <= x : cm-type

----- [tstr refl ]
P ⊢ x <= x : tstr

----- [bstr refl ]
P ⊢ x <= x : bstr

----- [uint refl ]
P ⊢ x <= x : uint
```
Note uint is treated as an identifier and not with numerical inequality.

A list of local-claims all must match for the list to match.
```
AND { P ⊢ clc <= elc : local-claim ... }
--------------------------------- [ [ + local-claim ] <= ]
P ⊢ [ clc ... ] <= [ elc ... ] : [ + local-claim ]
```

A local-claim can only match its _exact_ mkey and a subset of authorities.
```
cmv <= emv : measurement-values-map
ca <= ea : optional<[ + $crypto-key-type-choice]>
--------------------------------------------------- [ local-claim/measurement-map <= ]
[ mkey: mk, mval: cmv, authorities: ca ] <= [ mkey: mk, mval: emv, authorities: ea ] : local-claim
```

The measurement-values-map subset relation is defined on a per-codepoint basis, and with the optional<T> semantics.
I will not rehash the ordering of the right-hand-side codepoints here.
```
AND_{ cmvk => cmvv in cmvs } {
  some emvv := emvs[cmvk]
  P ⊢ cmvv <= emvv : measurement-values-order(P, cmvk)
}
--------------------------------------------------- [ measurement-values-map <= ]
P ⊢ cmvs <= emvs : measurement-values-map
```
The `measurement-values-order(none, uint)` definition is as defined for each of the measurement-values-map codepoints in the spec.

```
P ⊢ cclass <= eclass : optional<class-map>
P ⊢ cgroup <= egroup : optional<$group-id-type-choice>
P ⊢ cinstance <= einstance : optional<$instance-id-type-choice>
---------------------------------------------------------- [ environment-map <= ]
P ⊢ { cclass cgroup cinstance } <= { eclass egroup einstance } : environment-map
```

```
P ⊢ cclassid <= eclassid : optional<$class-id-type-choice>
⊢ cvendor <= evendor : optional<tstr>
⊢ cmodel <= emodel : optional<tstr>
⊢ clayer <= elayer : optional<uint>
⊢ cindex <= eindex : optional<uint>
---------- [ class-map <= ]
P ⊢ { cclassid cvendor cmodel  clayer cindex } <= { eclassid evendor emodel elayer eindex } : class-map
```

Authorities are matched with a subset relationship:

```
AND_{ ck in ca }{Exists ek in ea such that P ⊢ ck <= ek }
------------------------ [ authority <= ]
P ⊢ ca <= ea : [ + $crypto-key-type-choice ] 

A profile MAY define an ordering relation on $crypto-key-type-choice extensions, $class-id-type-choice, $group-id-type-choice, and $instance-id-type-choice may be defined by a profile. For the base CDDL choices, only CBOR-encoding-equality is a match.

```
crypto-key-ordering(p, ck, ek)
------------------------------- [ profile-defined crypto key type choice ordering ]
p ⊢ ck <= ek : $crypto-key-type-choice (not in base CDDL)
```

All of this setup gives much more structure to how a profile may impose extra matching semantics.

**Comment by nedmsmith** [comment]
> p  ⊢ ce <= ee : optional<environment-map>

I'm having difficulty understanding this because I'm not familiar with the notation and the variable names are terse.

**Comment by deeglaze** [comment]
The variables start with c or e for the condition ECT and entry ECT that are being compared, respectively. The rest of the variable comes from the fields of the ECT in the order specified in your revert PR.

Below the --- is the consequent. A goal you want to satisfy. Above the --- are the antecedents, the subgoals you need to discharge to satisfy the goal.

A turnstile ⊢ is notation from Frege. It roughly means "Given Premises ⊢ That which is proved". With added types ": type" you can further limit the deduction rules that apply to the goal. Our only premises are an optionally assumed profile.

**Comment by deeglaze** [comment]
Duplicate of #283
