### ISSUE TITLE
CoRIM should allow at most one profile

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#29]
Currently we allow 0..n profile(s) in the CoRIM.

There is no way a receiver can unambiguously identify which profile applies to which of the embedded CoMIDs / CoSWIDs, which makes the ingestion process unnecessarily brittle.

We should allow 0..1 instead, and explain that - if present - the profile applies to *all* the embedded CoMIDs & CoSWIDs.

**Comment by nedmsmith** [comment]
If profile A and profile B are part of the same Attester then an implementation that supports A also must support B. In this scenario, the subset of tags/triples that aligns with B would be required to be placed in a separate RIM. The verifier would check signatures for both and bring both into its internal set given some evidence conforms to A and some to B. 
The net is verifier does extra work checking signatures for no reduction in complexity.

**Comment by thomas-fossati** [comment]
A profile defines the domain of interpretation of what's found in the CoRIM bag.  If a CoRIM declares profile A as well as B then, when processing the embedded CoMID/CoSWID, the ingest logics needs to apply heuristics to decide whether the CoMID is to be interpreted according to A or B.  This becomes a real pain in the neck especially when A and B are quite but not exactly the same, in which case the risk for the heuristic to fire a false positive are pretty high.  Given the potential security risk associated with erroneous ingest of ref-vals & co, I'd rather err on the side of caution and accept the potential double signature penalty.

**Comment by nedmsmith** [comment]
Right. That’s a reasonable trade off.

Sent from my iPhone

On Nov 25, 2022, at 12:55 PM, Thomas Fossati ***@***.***> wrote:

﻿

A profile defines the domain of interpretation of what's found in the CoRIM bag. If a CoRIM declares profile A as well as B then, when processing the embedded CoMID/CoSWID, the ingest logics needs to apply heuristics to decide whether the CoMID is to be interpreted according to A or B. This becomes a real pain in the neck especially when A and B are quite but not exactly the same, in which case the risk for the heuristic to fire a false positive are pretty high. Given the potential security risk associated with erroneous ingest of ref-vals & co, I'd rather err on the side of caution and accept the potential double signature penalty.
