### ISSUE TITLE
cmtype is never used

### ISSUE THREAD

**Issue by deeglaze** [ietf-rats-wg/draft-ietf-rats-corim#297]
The cm-type is an enum in an ECT that has no functional purpose. I understand that it's an optional field of CMWs and it can be helpful for hinting, but there's internal representation stating that cm-type is a mandatory field despite never having a prescribed meaning outside of the enum. An `ae` definition doesn't say the ECTs will all have `cmtype: /evidence/ 2` for example. There's no mention of its use in result construction and how it is meant to feed into the CMW format.

Is this planned?

**Comment by thomas-fossati** [comment]
It's one of those things that look useful until you realise they've been sitting in a corner for years only to collect dust, so you throw them in the bin.  5 seconds later, you find yourself scraping the rubbish pile to try and get them back because you suddenly realise you need them :-)

**Comment by deeglaze** [comment]
Ah yes, to be clear I'm not saying bin it, I'm saying please explain it.

**Comment by nedmsmith** [comment]
The processing rules for RVs only applies to Evidence. If there is no way to distinguish message type then the RV processing could mistakenly be applied to Endorsements and other RVs.

**Comment by nedmsmith** [comment]
Like profile, cm-type doesn't have a way for a condition to match on these values, but like profile, the internal processing logic does need it.

**Comment by deeglaze** [comment]
evidence, reference values, and endorsements all talk about the same kinds of measurements. The role is really in who's doing the signing. I don't see why you would have to separate RVs from never applying to measurements added by an endorser. You end up needing to express the same thing just more verbosely by using a conditional endorsement that the measurements you want to see are the measurements you want to add your authority to.

**Comment by nedmsmith** [comment]
PR #299 more clearly articulates how cmtype plays a role in verifier processing. Is this incorrect?

**Comment by deeglaze** [comment]
That PR should satisfy this, yes.

**Comment by nedmsmith** [comment]
Fixed in #299
