### ISSUE TITLE
clarify CoRIM scope and their relationship with HBOM/SBOM

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#30]
Systems that build CoRIM might also be involved in building BOMs.  We should make it clear that although such systems are likely to use the same input data, CoRIM and BOMs are different objects, with separate scope/applicability.  A CoRIM serves the quite specific purpose of describing RATS target and attesting environments, in terms of their shape and aggregation, to attestation verifiers.  This generally involves a different level of abstraction than that required for a BOM.

**Comment by nedmsmith** [comment]
Close as this is being tracked by issue #40
