### ISSUE TITLE
Should `element-list` processing allow positional comparison

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#303]
The triple cddl allows mkey to be optional and multiple measurement-map entries to exist simultaneously. What should be Verifier behavior? There are two possibilities:

Option (1) fall back to positional comparison where the record at position i of the `condition` relation is compared with the record at position i of the ACS ECT.

Option (2) write normative text that bans multiplicity of measurement-map without mkey.

I'm leaning toward option 1.

**Comment by thomas-fossati** [comment]
Hmm, I have a personal distaste for positional semantics.

Besides, if one wants positional semantics for "anonymous" elements, they can use a `mkey` of type `uint` and define their matching algorithm, no?

So, leaning toward option 2, i.e., _"if multiple elements exist they `MUST NOT` be anonymous_".

**Comment by deeglaze** [comment]
I vote option 2.

**Comment by deeglaze** [comment]
@henkbirkholz @andrew-draper Your comments are requested.

**Comment by deeglaze** [comment]
I think there was a hint at an option 3.

(3) write normative text that if any `measurement-map` contains an `mkey`, then all `measurement-map` array elements must contain an `mkey`. If no `measurement-map` of the array contains an `mkey`, each element has an implicit `mkey` of its index in the array.

**Comment by deeglaze** [comment]
Slight twist,

(4) write normative text that if no measurement-map of the array contains an mkey, then each element has an implicit mkey of its index in the array.

This allows a missing mkey amongst many mkeys to be its own unit-type key that refers to the same element. I dislike this choice because it changes the meaning of other elements as soon as you add another that happens to have an mkey.

**Comment by nedmsmith** [comment]
Depending on the option selected, the language in Endorsement Triples Transformation {#sec-end-trans} can be softened.

**Comment by nedmsmith** [comment]
> This differs from (1) in that the mkey refers to the same element rather than the ith element based on the position in the array amongst other measurements with mkeys.

Wouldn't the ith element be the same as its index in the array?

**Comment by nedmsmith** [comment]
> write normative text that if any `measurement-map` contains an `mkey`, then all `measurement-map` array elements must contain an `mkey`

I expect the dominant use case for measurement-map will involve a singleton. Singletons don't need additional disambiguation. If an implementation begins with a singleton, but later adds a second, the onus is on the second to disambiguate it from the first. If the implementation of the second didn't touch the implementation of the first, it doesn't make sense that the first implementation should have to change. 

Language that mandated use of mkey for subsequent entries means there would only ever be one anonymous entry.

One of the profiles (psa/cca?) was overloading mkey to do more than simple disambiguation. I think this should be discouraged IMO. Other than that, the purpose for defining the namespace scope of mkey as "local" is primarily to disambiguate measurement-map multiples. It seems reasonable if the spec mandates use of mkey for multiples and allows a single anonymous entry.

**Comment by thomas-fossati** [comment]
> One of the profiles (psa/cca?) was overloading mkey to do more than simple disambiguation. I think this should be discouraged IMO.

We use `mkey`s in both CCA and PSA to disambiguate different firmware elements within the same TCB.  There is no more semantic than that.  I am unsure what you are referring to, but I would like to know because I don't want our design to diverge from "the CoRIM's way".

**Comment by nedmsmith** [comment]
> > One of the profiles (psa/cca?) was overloading mkey to do more than simple disambiguation. I think this should be discouraged IMO.
> 
> We use `mkey`s in both CCA and PSA to disambiguate different firmware elements within the same TCB. There is no more semantic than that. I am unsure what you are referring to, but I would like to know a bit more because I don't want our design to diverge from "the CoRIM's way".

I'm not an expert in ARM's use of mkey. Based on how it has been described to me the extension point is more complex than a simple identifier / label. I don't know how "TCB" differs from "environment" or "element".

**Comment by nedmsmith** [comment]
Option 5 - Allow a single anonymous entry. Subsequent entries MUST supply mkey. The location in the various measurement-map entries in the array is not significant.

**Comment by nedmsmith** [comment]
Is there consensus for option 5?

**Comment by thomas-fossati** [comment]
recording rough consensus on option 5.

**Comment by nedmsmith** [comment]
Closing issue - fixed by #315

**Comment by nedmsmith** [comment]
Fixed.
