### ISSUE TITLE
define matching rules for the "base" profile (i.e., DICE)

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#31]
We must clarify how a receiver is supposed to process unknown semantics.

Currently CoRIM does not have a way to say: _"if you don’t understand this triple you should abort processing, because it contains critical semantics."_

The implicit assumption (which we should clearly state) is that any such decision belongs to the definition of a CoRIM profile.

Additionally, we need to say
1. what is the default behaviour that all profiles should implement
2. what to do if a profile is not specified

**Comment by thomas-fossati** [comment]
As discussed.  We should define the "default profile" matching rules in the CoRIM base spec.  Other CoRIM profiles MUST define their own matching rules, including handling optionality, cardinality, etc. in their own spec.

**Comment by nedmsmith** [comment]
todo: document a verification flow that treats DICE matching as the default profile where DICE tcbinfo and concise-evidence are evidence inputs and corim is the endorsement and reference values inputs.

**Comment by nedmsmith** [comment]
Noting: https://github.com/ietf-rats-wg/draft-ietf-rats-corim/wiki/Notes-on-the-appraisal-flow

**Comment by yogeshbdeshpande** [comment]
https://ietf-rats-wg.github.io/draft-smith-rats-evidence-trans/draft-smith-rats-evidence-trans.html
