### ISSUE TITLE
corim-frags.mk for easier use in submodules

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#39]
corim-frags.mk lists the names of cddl files used to capture the various corim statements. When draft-ietf-rats-corim repo is a submodule to another repo, the list of cddl files are builid dependencies for profiles that depend on them. The list of dependencies needs to be updated if the corim repo updates the list.

It is difficult to reuse the corim-frags.mk file in  a parent makefile because the pathnames default to the current folder. If the corim-frags.mk included a pathname macro then the parent makefile could define the pathname macro. 

For example if an entry in corim-frags.mk was something like `CORIM_FRAGS += $(CORIM_DIR)/corim.cddl` and the parent makefile defined `CORIM_DIR := draft-ietf-rats-corim/cddl` then when the corim-frags.mk is imported into the parent makefile, the correct submodule path to the dependent files could be added without reentering a long list of dependencies.

**Comment by thomas-fossati** [comment]
Unless I've misunderstood your requirement, it seems to me that what you need could be achieved without needing to fiddle with the CoRIM build system:

For example, if your dependent project includes this repo in a sub-folder named `corim-base`:

```sh
├── Makefile
├── corim-base
│   ├── CONTRIBUTING.md
│   ├── Gemfile
│   ├── LICENSE.md
│   ├── Makefile
│   ├── README.md
│   ├── cddl
...
└── my-comid-extn.cddl
```

and your `my-comid-extn.cddl` is something like:
```cddl
my-comid-extn = {
  0 => "my CoMID extn"
  1 => concise-mid-tag
}
```

then you can drive the build process with a `Makefile` that looks like:
```make
all: autogen.cddl

CORIM_BASE := corim-base/cddl/

include $(CORIM_BASE)comid-frags.mk

REL_COMID_FRAGS := $(addprefix $(CORIM_BASE),$(COMID_FRAGS))

COSWID := $(CORIM_BASE)/concise-swid-tag.cddl

$(COSWID): ; $(MAKE) -C $(CORIM_BASE)

autogen.cddl: my-comid-extn.cddl $(COSWID)
	@for f in my-comid-extn.cddl $(REL_COMID_FRAGS) ; do cat $$f >> $@ ; done
	@cddl $@ g 1
```

**Comment by thomas-fossati** [comment]
As agreed the suggestion in https://github.com/ietf-rats-wg/draft-ietf-rats-corim/issues/39#issuecomment-1448653050 is deemed sufficient to resolve the issue.
