### ISSUE TITLE
BOM tag

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#40]
In the 11th Jan 2023 meeting we have identified the need for a new BOM (bill of material) object that tells the verifier what a *complete* set of tags looks like.

The BOM object must list all the needed tags (CoMID, CoSWIDs, CoTS) using their IDs.

Additionally, the BOM will indicate the validity period of the aggregate.

A BOM object represents the signal for the verifier to *activate* the listed tags.  Data contained in a tag must not be used for appraisal until a BOM which activates that tag is received and successfully processed.  All the tags listed in the BOM must be activated in the same transaction, i.e., either all or none.

**Comment by nedmsmith** [comment]
The constrained BOM (CoBOM?) would likely borrow from concise-mid-tag ? &(linked-tags: 3) => [ + linked-tag-map ] as a way to relate the various tags under a common BOM.

There is an expectation that the list of 'linked-tags' in the BOM is an acyclic graph. Possibly, the function a CoBOM issuer performs is to check for cycles?

Possible CDDL:
```
concise-bom-tag = {
  &(linked-tags: 0) => [ + linked-tag-map ],
  &(validity: 1) => validity-map
}

$concise-tag-type-choice /= #6.507(bytes .cbor concise-bom-tag)
```

**Comment by thomas-fossati** [comment]
We also need a unique ID for the BOM for ref-counting the referenced tags and decide when they can be wiped out.

And also for "partial" CoRIMs to reference their parent BOM.

**Comment by thomas-fossati** [comment]
There is another interesting use case for linking BOMs horizontally (say for expressing update semantics).  That would need another link relation.

**Comment by yogeshbdeshpande** [comment]
For link relationship a most common and obvious use case is that the Specific BOM Tag ID gets updated, to add new endorsements (i .e. CoMID list is modified to incorporate new endorsements). Hence the new BOM  Tag ID updates the existing BOM Tag ID

**Comment by nedmsmith** [comment]
> For link relationship a most common and obvious use case is that the Specific BOM Tag ID gets updated, to add new endorsements (i .e. CoMID list is modified to incorporate new endorsements). Hence the new BOM Tag ID updates the existing BOM Tag ID

Is there semantic differential between a BOM update and a BOM replacement? If not the 'replaces' relationship type might work. Replaces semantic is that previously issued tags are discarded. That seems appropriate for a BOM.

**Comment by nedmsmith** [comment]
> There is another interesting use case for linking BOMs horizontally (say for expressing update semantics). That would need another link relation.

I'm not following the use case for 'horizontal' BOMs. Isn't the idea that one entity is authorized / trusted to know which tags belong in the BOM? What would it mean to a Verifier to have multiple (conflicting) trusted BOMs / BOM providers?

**Comment by nedmsmith** [comment]
> We also need a unique ID for the BOM for ref-counting the referenced tags and decide when they can be wiped out.

Reusing tag-identity-map as the unique ID. Also, concise TA stores might be using #6.507?
Here is an updated proposed CDDL for BOM.
```
concise-bom-tag = {
  &(tag-identity: 0) => tag-identity-map
  &(linked-tags: 1) => [ + linked-tag-map ],
  &(validity: 2) => validity-map
}
$concise-tag-type-choice /= #6.508(bytes .cbor concise-bom-tag)
```

**Comment by nedmsmith** [comment]
> A "Replace" would mean that the existing old TAG-ID is over-written,

I thought we defined 'replaces' semantics to be that the tag-id remains the same, but the tag version number is incremented. This was to preserve referential integrity based on tag-id.

Update semantics means two tags (different IDs) could exist at the same time. Verifier has to determine which tag to use. Normally, this is done by Attester reporting which version of thing it is or by policy that has an allow/deny list that includes/excludes one of the tags. 

The use case for multiple valid BOMs (for the same version of thing) doesn't make sense to me.

**Comment by yogeshbdeshpande** [comment]
_I thought we defined 'replaces' semantics to be that the tag-id remains the same, but the tag version number is incremented. This was to preserve referential integrity based on tag-id._
@nedmsmith This will make the construct complicated, as the Verifier has to throw the old list without been explicit command for deletion!
