### ISSUE TITLE
allow key thumbprints as `authorized-by`

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#51]
We currently allow raw keys, certified keys and cert chains as `authorized-by` types.

Another form of `authorized-by` could be a key thumbprint (e.g., PSA signer ID).

**Comment by nedmsmith** [comment]
agree.

**Comment by thomas-fossati** [comment]
Cool, what about:

```cddl
$crypto-key-type-choice /= tagged-thumbprint-type

tagged-thumbprint-type = #6.557(hash-entry)
```
where `hash-entry` is the usual alg-id & value compound.

With the understanding that the receiver either:
* knows what is the hashed object is (and can therefore reconstruct it and match), or
* uses `hash-entry.hash-value` as an opaque lookup handler

**Comment by nedmsmith** [comment]
Per the thread on reducing dependency on coswid / hash-entry. Should this PR be updated to use `COSE_CertHash = [ hashAlg: (int / tstr), hashValue: bstr ]` ?

**Comment by thomas-fossati** [comment]
> Per the thread on reducing dependency on coswid / hash-entry. Should this PR be updated to use `COSE_CertHash = [ hashAlg: (int / tstr), hashValue: bstr ]` ?

I sense some browser tab mismatch here :-) This is an issue, not a PR.

But if I understand your intent correctly, I'd prefer to keep the PR separate (and scoped to their issue), i.e., if we agree on the `COSE_CertHash` approach I will file another PR for that.
