### ISSUE TITLE
use `COSE_CertHash`-style digest description in lieu of `hash-entry`

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#54]
We currently import `hash-entry` from CoSWID:

```cddl
hash-entry = [
  hash-alg-id: int
  hash-value: bytes
]
```
which forces hash algorithm identifiers to be integer codes from IANA's [named-information](https://www.iana.org/assignments/named-information/named-information.xhtml) registry.

That's great, but imposes a dependency on yet another registry.

We could take instead the more merciful approach taken by RFC9360:

```cddl
COSE_CertHash = [ hashAlg: (int / tstr), hashValue: bstr ]
```

which allows, for alg-ids, strings as an alternative to code points.

**Comment by nedmsmith** [comment]
I'm not passionate about it either way.
