### ISSUE TITLE
rework the CoRIM Intro

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#6]
Text (temporarily) expunged:

```
Concise Reference Integrity Manifests (CoRIM) contain tags that describe the
composition and measurements of a platform, device, component, or software.

CoRIM is an envelope to carry information typically exchanged between Endorsers
and Verifiers {{-rats-arch}}. Endorsements are information produced by
Endorsers and consumed by Verifiers. CoRIM contains Endorsement Claims. Inside
CoRIM, Claims about hardware or firmware are described using CoMID tags.
Software Claims are described using CoSWID tags.

CoRIM can be integrity protected and authenticated using cryptography. The
CoRIM signer is the entity that asserts Endorsement Claims.  In a complex
supply chain, it is likely multiple Endorsers will produce CoRIMs, pertaining
to individual components they produce, at different times. Hence a CoRIM can
provide a link to other CoRIMs such that a combination of CoRIMs describe a
device class.
```

There are a couple of problems with that text:

1. it mentions RATS-ARCH but does not use the vocabulary correctly (specifically, it squashes together endorsements and ref-values into endorsements -- and their providers are merged accordingly)
2. there are some other clarity issues that popped up in a quick skimming session before submission of -03

**Comment by henkbirkholz** [comment]
Every big topic needs its introduction. E.g. the whole document as discussed in #4

the list of topics include:
* CoRIM docuement
* BOM
* CoMID
* reference to CoSWID

**Comment by yogeshbdeshpande** [comment]
Some of the sections referenced in this issue, especially CoRIM Introduction and CoMID Introduction is addressed by:
https://github.com/ietf-rats-wg/draft-ietf-rats-corim/pull/68
