### ISSUE TITLE
CoMID intro

### ISSUE THREAD

**Issue by thomas-fossati** [ietf-rats-wg/draft-ietf-rats-corim#7]
Provide an introduction to CoMID that contain at least:

* An overview of the CoMID model
* A big-picture pic of the data structures and their relationships

Also think of where to put the triples high level description. Does that go only here or also detailed in §3.1.4 ?

**Comment by nedmsmith** [comment]
I'm not sure what a 'category' is in §3.1.4. Also category should be categories in second sentence. The section 3 issue#88 seems to suggest that an overview of the structures / big picture belongs here.

**Comment by yogeshbdeshpande** [comment]
This issue is addressed by: https://github.com/ietf-rats-wg/draft-ietf-rats-corim/pull/68
