### ISSUE TITLE
tagged-concise-mid-tag and other tagged type definitions needed

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#74]
There should be tagged `tagged-` definitions for the various types of tags that can be included in a corim.
for example a corim can contain these CBOR tagged structures:
```
$concise-tag-type-choice /= #6.505(bytes .cbor concise-swid-tag)
$concise-tag-type-choice /= #6.506(bytes .cbor concise-mid-tag)
$concise-tag-type-choice /= #6.508(bytes .cbor concise-bom-tag)
```
but we don't have a way to refer to each as a CBOR tagged statement, such as:
```
tagged-concise-swid-tag = #6.505(bytes .cbor concise-swid-tag)
tagged-concise-mid-tag = #6.506(bytes .cbor concise-mid-tag)
tagged-concise-bom-tag = #6.508(bytes .cbor concise-bom-tag)
```
The $concise-tag-type-choice definitions could become:
```
$concise-tag-type-choice /= tagged-concise-swid-tag
$concise-tag-type-choice /= tagged-concise-mid-tag
$concise-tag-type-choice /= tagged-concise-bom-tag
```

**Comment by thomas-fossati** [comment]
WFM

Do you plan to use the tagged payloads outside the CoRIM context?

**Comment by nedmsmith** [comment]
Yes. There is a use case for attestation results that copies Verifier input into attestation results and a use case that borrows from conditional-endorsed-triple-record. Otherwise, it is motivated generally by consistent naming convention.

**Comment by thomas-fossati** [comment]
ok, thanks for providing extra context.
