### ISSUE TITLE
profile-type-choice is not a type-choice

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#77]
Note that `profile-type-choice = uri / tagged-oid-type` isn't an extensible type.
Given EAT profiles are defined differently: `general-uri / general-oid` and it makes sense to have profiles in other attestation messages such as AR and potentially appraisal policies.
It makes sense to define an extensible profile type.

Ideally:
```
$profile-type-choice /= uri
$profile-type-choice /= tagged-oid-type
$profile-type-choice /= general-uri
$profile-type-choice /= general-oid
```
and then
```
corim-map = {
...
  ? &(profile: 3) => $profile-type-choice
...
}
```

**Comment by thomas-fossati** [comment]
not sure what is the advantage of having essentially duplicated semantics?

**Comment by yogeshbdeshpande** [comment]
@thomas-fossati Can you please clarify what do you mean by duplicated semantics?
Where is the duplication? Do you mean between eat profile versus corim profile or something else?

**Comment by thomas-fossati** [comment]
> @thomas-fossati Can you please clarify what do you mean by duplicated semantics?
> Where is the duplication? Do you mean between eat profile versus corim profile or something else?

I mean between `general-uri` and `uri` on one side and `tagged-oid-type` and `general-oid`.

**Comment by yogeshbdeshpande** [comment]
We started with uri and oid. I am just making a small change to correct the syntax.

If you want to extend it to eat profile semantics, then please raise a separate github issue

**Comment by thomas-fossati** [comment]
> We started with uri and oid. I am just making a small change to correct the syntax.

My comment is on the issue, not on the PR.

**Comment by yogeshbdeshpande** [comment]
I think the text description of the issue is a bit mis-leading!

It should be profile-type-choice is not expressed in the CDDL as an extensible type choice
