### ISSUE TITLE
domain-type-choice should support OIDs

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#78]
$domain-type-choice currently is:
```
$domain-type-choice /= uint
$domain-type-choice /= text
$domain-type-choice /= tagged-uuid-type
```
It is reasonable that an Environment identifier doubles as a domain for example a top level "device" environment may have endorsed values that apply to the entire device such as 'device-X is common criteria certified'. Device X would be a described by an endorsed-values-triple-record containing an environment-map and class-id in the form of a `$class-id-type-choice` .
```
$class-id-type-choice /= tagged-oid-type
$class-id-type-choice /= tagged-uuid-type
$class-id-type-choice /= tagged-int-type
```
There is existing overlap for `tagged-uuid-type` and the `tagged-int-type` and `uint` types could be easily mapped to achieve the use case goal. The `tagged-uuid-type` to domain id mapping could be achieved using `text` that contains an ascii OID representation, but that seems problematic. It is safer to add `tagged-oid-type` to `$domain-type-choice`.

**Comment by yogeshbdeshpande** [comment]
Closing as already fixed by PR #79
