### ISSUE TITLE
Verifier behavior for tagged-thumbprint-type

### ISSUE THREAD

**Issue by nedmsmith** [ietf-rats-wg/draft-ietf-rats-corim#84]
The `tagged-thumbprint-type` is used by `$crypto-key-type-choice` which is used in the `identity-triple-record`, `attest-key-triple-record` and `authorized-by` code point in various other structures. The verifier behavior for `tagged-thumbprint-type` could be interpreted different ways that are not documented. Both the identity and attest-key triples' descriptions indicate use of the key is a prerequisite. A key digest can't be used directly to verify private key usage. The verifier needs the public key. There could be two cases where the key is verified, (a) verified directly by the verifier who must use the digest to find the key, (b) verified by split verifiers where a first verifier does a signature check and a second verifier completes the signature check by checking CRLs and does certificate path validation. For (b), the first verifier may use `tagged-thumbprint-type` to identify the partially verified key such that the second verifier completes the process. It's assumed that the second verifier has a way to trust the first verifier.

The `tagged-thumbprint-type` definition says the digest could be of a raw key or a certificate. This implies the verifier maintains a lookup table for both or that there is enough context in the triple for the verifier to know which type of lookup is appropriate. Possibly, it makes sense to define a new thumbprint type for certificate and constrain the current thumbprint type to keys only to avoid verifier having to have additional context?

`tagged-thumbprint-type = #6.557(digest)` is described as a key thumbprint
`tagged-cert-thumbprint-type = #6.559(digest)` is described as a certificate thumbprint

Language for tagged thumbprints should describe the split verifier scenario where the first verifier performs the signature check and the second verifier performs CRL / cert status and path validation checks.

**Comment by yogeshbdeshpande** [comment]
Please also refer to : https://github.com/ietf-rats-wg/draft-ietf-rats-corim/issues/82

**Comment by nedmsmith** [comment]
Fixed by #85
